theme = "onedark"

[keys.insert]

"C-[" = "normal_mode"
"C-c" = "normal_mode"
"A-ret" = "open_below"
"C-s" = "goto_first_nonwhitespace"

[keys.select]

"C-s" = ":w"
"C-[" = "normal_mode"
"C-c" = "normal_mode"
r = ["replace", "normal_mode"]
R = ["replace_with_yanked", "normal_mode"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"

[keys.normal]
# "A-s" = "move_line_down" # Maps the 'a' key to the move_char_left command
"C-l" = ":lsp-restart"
"C-s" = ":w"
"C-o" = ":config-open"
"ret" = ["add_newline_below"]
"S-ret" = ["add_newline_above"]
"C-d" = ["half_page_down", "align_view_center"]
"C-u" = ["half_page_up", "align_view_center"]
"C-up" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_up", "paste_before", "move_line_up", "goto_line_end", "search_next"]
"C-down" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_down", "paste_before", "move_line_up", "goto_line_end", "search_next"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
R = ["replace_selections_with_clipboard", "normal_mode"]
Y = "yank_main_selection_to_clipboard"

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]

space = "all"

[editor.lsp]

display-messages = true

[editor]

line-number = "relative"
bufferline = "multiple"

# [editor.file-picker]
# hidden = false