[[language]]
name = "rust"
auto-format = false

[[language]]
name = "python"
indent = { tab-width = 1, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "go"
auto-format = false
indent = { tab-width = 4, unit = " " }
